[workspace]

members = [
    "lunch-list-backend",
    "lunch-list-frontend",
]

[profile.release]
lto = true

[profile.release.package.lunch-list-frontend]
# Tell `rustc` to optimize for small code size.
opt-level = "z"
