version: "3"
services:

  redis:
    image: redis:alpine
    entrypoint: redis-server --appendonly yes
    volumes:
      - ./redis-data:/data
    ports:
      - "6379:6379"
    networks:
      - backend

  lunch-list:
    build: .
    image: docker.pkg.github.com/olavhaasie/lunch-list/lunch-list
    env_file: .env
    ports:
      - "46018:46018"
    networks:
      - backend
    depends_on:
      - redis

networks:
  backend:

