version: "3"
services:

  redis:
    image: redis:alpine
    entrypoint: redis-server --appendonly yes
    volumes:
      - ./redis-data:/data
    ports:
      - "6379:6379"
    networks:
      - backend

  api:
    build:
      context: .
      args:
        port: "46018"
        redis_host: "redis"
    image: lunch-list
    ports:
      - "40618:40618"
    networks:
      - backend
    depends_on:
      - redis

networks:
  backend:

