name: Rust

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        release_channel: [stable, beta, nightly]

    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: ${{ matrix.release_channel }}
        components: clippy, rustfmt
        target: wasm32-unknown-unknown
        override: true
    - name: Build backend
      run: cargo build --verbose -p lunch-list-backend
    - name: Build frontend
      run: cargo build --verbose -p lunch-list-frontend --target wasm32-unknown-unknown
    - name: Run backend tests
      run: cargo test --verbose -p lunch-list-backend
    - name: Check fmt
      run: cargo fmt -- --check
    - name: Run clippy
      run: cargo clippy

